trigger:
  branches:
    include:
      - main

variables:
  - group: hello-app-variables

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: Docker@2
            inputs:
              command: buildAndPush
              repository: $(DOCKER_USERNAME)/noventiq
              Dockerfile: $(DOCKER_USERNAME)/noventiq
              tags: latest
              containerRegistry: DockerHubConnection

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployToAKS
        environment: aks
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: HelmInstaller@1
                  inputs:
                    helmVersionToInstall: 'latest'

                - task: HelmDeploy@0
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: 'Azure-Service-Connection'
                    azureResourceGroup: 'Your-RG'
                    kubernetesCluster: 'Your-AKS-Cluster'
                    namespace: '$(AKS_NAMESPACE)'
                    command: upgrade
                    chartType: filepath
                    chartPath: hello-app-chart
                    releaseName: hello-app
                    overrideValues: |
                      image.repository=$(DOCKER_USERNAME)/noventiq
                      image.tag=$(IMAGE_TAG)
                      env.DB_PASSWORD=$(DB_PASSWORD)

                - script: |
                    curl http://<your-app-loadbalancer>/health
                  displayName: "Health Check"
