apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-deploy
  template:
    metadata:
      labels:
        app: sql-deploy
    spec:
      containers:
        - name: sql-deploy
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pvc
        - name: restore-volume
          hostPath:                       # This is for local testing only
            path: /mnt/data/restore       # You place your .bak file here before deployment
            type: Directory
